### PR TITLE
[WIP] Classical ML release

### PR DESCRIPTION
**Pull request by mathijsb**

### CODE REVIEW

**Comment by janjongboom** [comment]
LinearRegression/train.py still has jax references.

**Comment by janjongboom** [comment]
```
$ python3.9 train.py --data-directory data/ --out-directory out/ --solver newton-cholesky
ValueError: Buffer dtype mismatch, expected 'const float' but got 'double'
```

**Comment by janjongboom** [comment]
When importing into Edge Impulse:

```
Python 3.10.13
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LabelBinarizer from version 1.4.0 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RidgeClassifier from version 1.4.0 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LabelBinarizer from version 1.4.0 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RidgeClassifier from version 1.4.0 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
2024-02-02 12:27:06.860345: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
2024-02-02 12:27:06.860392: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
```

**Comment by janjongboom** [comment]
Tested with https://github.com/edgeimpulse/example-custom-ml-block-xgboost and it fails with:

```
Python 3.10.13
[LightGBM] [Fatal] Could not open /home/model.txt
Traceback (most recent call last):
  File "/app/convert_model.py", line 41, in <module>
    clf = lgb.Booster(model_file=args.model_file)
  File "/usr/local/lib/python3.10/dist-packages/lightgbm/basic.py", line 2639, in __init__
Loading LGBM model...
    _safe_call(_LIB.LGBM_BoosterCreateFromModelfile(
  File "/usr/local/lib/python3.10/dist-packages/lightgbm/basic.py", line 125, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: Could not open /home/model.txt
Return code was not 0, but 1
```

**Comment by mathijsb** [comment]
> Tested with https://github.com/edgeimpulse/example-custom-ml-block-xgboost and it fails with:
> 
> ```
> Python 3.10.13
> [LightGBM] [Fatal] Could not open /home/model.txt
> Traceback (most recent call last):
>   File "/app/convert_model.py", line 41, in <module>
>     clf = lgb.Booster(model_file=args.model_file)
>   File "/usr/local/lib/python3.10/dist-packages/lightgbm/basic.py", line 2639, in __init__
> Loading LGBM model...
>     _safe_call(_LIB.LGBM_BoosterCreateFromModelfile(
>   File "/usr/local/lib/python3.10/dist-packages/lightgbm/basic.py", line 125, in _safe_call
>     raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
> lightgbm.basic.LightGBMError: Could not open /home/model.txt
> Return code was not 0, but 1
> ```

Fixed this on byom-pickle-import branch

**Pull request merged**
